backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"     # where uploaded images go in your repo
public_folder: "/images/uploads"   # how the site accesses them

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
