backend:
  name: git-gateway
  branch: main
  publish_mode: simple


media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Welcome Text", name: "welcome", widget: "string" }

