backend:
  name: git-gateway
  branch: preview #edit on preview; PR later

media_folder: "images/uploads"     # where uploaded images go in your repo
public_folder: "/images/uploads"   # how the site accesses them

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Content"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home.json"
        format: json
        fields:
          - { label: "Background Image", name: "bgImage", widget: "image" }

      
